  headers <- list(
    "group_aux" = c(
      "AGENT NAME",
      "LOGIN ID",
      "STAFFED TIME",
      "AUX TIME",
      "TIME IN STARTUP TIME",
      "TIME IN TRAIN, MEET, PROJECT",
      "TIME IN CALL COACHING",
      "TIME IN SYSTEM ISSUES",
      "TIME IN CASE WORK",
      "TIME IN EXTERNAL SUPPORT",
      "TIME IN UNSCHEDULED BREAK",
      "TIME IN LUNCH",
      "TIME IN BREAK",
      "TIME IN OTHER PRODUCTIVE WORK",
      "TIME IN AUX 10-99"
    ),
    "group_summary" = c(
      "AGENT NAME",
      "ACD CALLS",
      "AVG. ACD TIME",
      "AVG. ACW TIME",
      "% AGENT OCCUPANCY W/ ACW",
      "% AGENT OCCUPANCY W/O ACW",
      "EXTN IN CALLS",
      "AVG. EXTN IN TIME",
      "EXTN OUT CALLS",
      "AVG. EXTN OUT TIME",
      "ACD TIME",
      "ACW TIME",
      "AGENT RING TIME",
      "OTHER TIME",
      "AUX TIME",
      "AVAILABLE TIME",
      "STAFFED TIME"
    ),
    "group_performance" = c(
      "AGENT NAME",
      "ACD CALLS",
      "HELD CALLS",
      "AVG. ACD TIME",
      "AVG. CALL RELATED ACW TIME",
      "AVG. TOTAL ACW TIME",
      "AVG. NON-CALL RELATED ACW TIME",
      "AVG. HOLD TIME",
      "AVG. HANDLE TIME",
      "AVAILABLE TIME",
      "UNSCHEDULED AUX TIME",
      "STAFFED TIME",
      "% ACD TIME",
      "% CALL RELATED ACW",
      "% TOTAL ACW",
      "% UN-SCHEDULED AUX",
      "ACD CALLS RELEASED"
    )
  )